"""
Django settings for BKBBlog project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-al-1#x1yoyxbu-+c*8moms)_7j!y^&mx%@wwv^w6)w$v5yqyh1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Default Django applications for admin, authentication, contenttypes, sessions, messages, and static files
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add article application
    'article',
    # Add user application(not necessary since not any model creaion is needed, therefore there is no need for any migration)
    'user',
    # Add crispy_forms application
    'crispy_forms',
    # Add crispy_bootstrap application for using crispy forms with bootstrap4
    'crispy_bootstrap4',
    # Add ck editor application
    'ckeditor',
    # Add django cleanup application
    'django_cleanup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BKBBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Find templates in the templates folder
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'BKBBlog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

"""
 This line defines the 'STATICFILES_DIRS' variable as a tuple containing a single element
 The element is a string that is a path to the 'static' directory located in the project's base directory (as defined by 'BASE_DIR')
 This variable is used to tell Django where to find additional static files, 
 such as those that are specific to your project and not part of an installed app
"""
STATICFILES_DIRS = (
    # Path to the 'static' directory
    os.path.join(BASE_DIR, 'static'),
)

# Set the static root directory for collecting static files during deployment
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Set the allowed template packs for crispy-forms to 'bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
# Set the default template pack for crispy-forms to 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Configuration settings for CKEditor
CKEDITOR_CONFIGS = {
    "default" : {
        "removePlugins" : "stylesheetparser",
        "allowedContent" : True,
        "width" : "100%",
    }
}

# Set the URL and root directory for media files
MEDIA_URL = "/media/"
MEDIA_ROOT= os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
